//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsTest.ucc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ucc.ess.azry.com/", ConfigurationName="ucc.UCCServicesWCF")]
    public interface UCCServicesWCF {
        
        // CODEGEN: Generating message contract since the operation getPayment is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPaymentWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.ucc.getPaymentResponse1 getPayment(WinFormsTest.ucc.getPaymentRequest request);
        
        // CODEGEN: Generating message contract since the operation getPayments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPaymentsWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.ucc.getPaymentsResponse1 getPayments(WinFormsTest.ucc.getPaymentsRequest request);
        
        // CODEGEN: Generating message contract since the operation getServiceProviders is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getServiceProviderWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.ucc.getServiceProvidersResponse1 getServiceProviders(WinFormsTest.ucc.getServiceProvidersRequest request);
        
        // CODEGEN: Generating message contract since the operation reconcile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:reconcileWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.ucc.reconcileResponse1 reconcile(WinFormsTest.ucc.reconcileRequest request);
        
        // CODEGEN: Generating message contract since the operation registerClearingOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:registerClearingOrderWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.ucc.registerClearingOrderResponse1 registerClearingOrder(WinFormsTest.ucc.registerClearingOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
    public partial class getPayment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
                this.RaisePropertyChanged("paymentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class registerClearingOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UCCFault uccErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UCCFault uccError {
            get {
                return this.uccErrorField;
            }
            set {
                this.uccErrorField = value;
                this.RaisePropertyChanged("uccError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class UCCFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UCCError errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UCCError errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public enum UCCError {
        
        /// <remarks/>
        SYSTEM_INTERNAL_ERROR,
        
        /// <remarks/>
        UNKNOWN_BUSINESS_DAY,
        
        /// <remarks/>
        UNKNOWN_SERVICE_PROVIDER,
        
        /// <remarks/>
        UNKNOWN_PAYMENT,
        
        /// <remarks/>
        UNKNOWN_SERVICE,
        
        /// <remarks/>
        ILLEGAL_CLEARING_PAYMENT,
        
        /// <remarks/>
        ILLEGAL_CLEARING_CURRENCY,
        
        /// <remarks/>
        ILLEGAL_CLEARING_SP_CODE,
        
        /// <remarks/>
        WRONG_CLEARING_AMOUNT,
        
        /// <remarks/>
        NON_UNIQUE_BANK_ORDER_NUMBER,
        
        /// <remarks/>
        NON_UNIQUE_AGENT_PAYMENT_ID,
        
        /// <remarks/>
        NON_UNIQUE_BUSINESS_DAY_ID,
        
        /// <remarks/>
        COMMISSION_CALCULATION_ERROR,
        
        /// <remarks/>
        WRONG_CANCEL_AMOUNT,
        
        /// <remarks/>
        WRONG_CANCEL_CURRENCY,
        
        /// <remarks/>
        PAYMENT_CANCELLING,
        
        /// <remarks/>
        PAYMENT_ALREADY_CANCELED,
        
        /// <remarks/>
        PAYMENT_FAILED,
        
        /// <remarks/>
        PAYMENT_BUSINESS_DAY_CLOSED,
        
        /// <remarks/>
        RECONCILIATION_ALREADY_PERFORMED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class ClearingOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankOrderDocumentNumberField;
        
        private string serviceProviderCodeField;
        
        private float amountField;
        
        private string currencyField;
        
        private string paymentPurposeField;
        
        private string additionalInfoField;
        
        private string payerNameField;
        
        private string payerIdentificationNumberField;
        
        private string treasuryCodeField;
        
        private System.DateTime clearingTimeField;
        
        private string receiverBankCodeField;
        
        private string receiverBankAccountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bankOrderDocumentNumber {
            get {
                return this.bankOrderDocumentNumberField;
            }
            set {
                this.bankOrderDocumentNumberField = value;
                this.RaisePropertyChanged("bankOrderDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceProviderCode {
            get {
                return this.serviceProviderCodeField;
            }
            set {
                this.serviceProviderCodeField = value;
                this.RaisePropertyChanged("serviceProviderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string paymentPurpose {
            get {
                return this.paymentPurposeField;
            }
            set {
                this.paymentPurposeField = value;
                this.RaisePropertyChanged("paymentPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string payerName {
            get {
                return this.payerNameField;
            }
            set {
                this.payerNameField = value;
                this.RaisePropertyChanged("payerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string payerIdentificationNumber {
            get {
                return this.payerIdentificationNumberField;
            }
            set {
                this.payerIdentificationNumberField = value;
                this.RaisePropertyChanged("payerIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string treasuryCode {
            get {
                return this.treasuryCodeField;
            }
            set {
                this.treasuryCodeField = value;
                this.RaisePropertyChanged("treasuryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime clearingTime {
            get {
                return this.clearingTimeField;
            }
            set {
                this.clearingTimeField = value;
                this.RaisePropertyChanged("clearingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string receiverBankCode {
            get {
                return this.receiverBankCodeField;
            }
            set {
                this.receiverBankCodeField = value;
                this.RaisePropertyChanged("receiverBankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string receiverBankAccount {
            get {
                return this.receiverBankAccountField;
            }
            set {
                this.receiverBankAccountField = value;
                this.RaisePropertyChanged("receiverBankAccount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class ReconcilationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessDayStatus businessDayStatusField;
        
        private float expectedPaymentsAmountField;
        
        private int expectedPaymentsNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BusinessDayStatus businessDayStatus {
            get {
                return this.businessDayStatusField;
            }
            set {
                this.businessDayStatusField = value;
                this.RaisePropertyChanged("businessDayStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float expectedPaymentsAmount {
            get {
                return this.expectedPaymentsAmountField;
            }
            set {
                this.expectedPaymentsAmountField = value;
                this.RaisePropertyChanged("expectedPaymentsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int expectedPaymentsNumber {
            get {
                return this.expectedPaymentsNumberField;
            }
            set {
                this.expectedPaymentsNumberField = value;
                this.RaisePropertyChanged("expectedPaymentsNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public enum BusinessDayStatus {
        
        /// <remarks/>
        OPENED,
        
        /// <remarks/>
        CLOSED_NORMAL,
        
        /// <remarks/>
        CLOSED_IRREGULAR,
        
        /// <remarks/>
        CLOSED_AFTER_REVISION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class reconcileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReconcilationResult reconcilationResultField;
        
        private UCCFault uccErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ReconcilationResult reconcilationResult {
            get {
                return this.reconcilationResultField;
            }
            set {
                this.reconcilationResultField = value;
                this.RaisePropertyChanged("reconcilationResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UCCFault uccError {
            get {
                return this.uccErrorField;
            }
            set {
                this.uccErrorField = value;
                this.RaisePropertyChanged("uccError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class ServiceCommission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float minAmountField;
        
        private float maxAmountField;
        
        private string currencyField;
        
        private string serviceConsumerCodeField;
        
        private string paymentChannelField;
        
        private float commissionFixedField;
        
        private float commissionPercentField;
        
        private float minCommissionField;
        
        private float maxCommissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float minAmount {
            get {
                return this.minAmountField;
            }
            set {
                this.minAmountField = value;
                this.RaisePropertyChanged("minAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float maxAmount {
            get {
                return this.maxAmountField;
            }
            set {
                this.maxAmountField = value;
                this.RaisePropertyChanged("maxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string serviceConsumerCode {
            get {
                return this.serviceConsumerCodeField;
            }
            set {
                this.serviceConsumerCodeField = value;
                this.RaisePropertyChanged("serviceConsumerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string paymentChannel {
            get {
                return this.paymentChannelField;
            }
            set {
                this.paymentChannelField = value;
                this.RaisePropertyChanged("paymentChannel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float commissionFixed {
            get {
                return this.commissionFixedField;
            }
            set {
                this.commissionFixedField = value;
                this.RaisePropertyChanged("commissionFixed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float commissionPercent {
            get {
                return this.commissionPercentField;
            }
            set {
                this.commissionPercentField = value;
                this.RaisePropertyChanged("commissionPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float minCommission {
            get {
                return this.minCommissionField;
            }
            set {
                this.minCommissionField = value;
                this.RaisePropertyChanged("minCommission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float maxCommission {
            get {
                return this.maxCommissionField;
            }
            set {
                this.maxCommissionField = value;
                this.RaisePropertyChanged("maxCommission");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class Service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceCodeField;
        
        private string descriptionField;
        
        private string verifyServiceCodeField;
        
        private string debtServiceCodeField;
        
        private string payServiceCodeField;
        
        private string cancelServiceCodeField;
        
        private string abonentDetailsPatternField;
        
        private bool activeField;
        
        private bool allAgentAccountsField;
        
        private byte[] serviceIconField;
        
        private bool oneTimePaymentField;
        
        private bool immediateTransactionField;
        
        private bool additionalInfoField;
        
        private bool transferCommissionsField;
        
        private bool phoneAbonentCodeField;
        
        private ServiceCommission[] serviceCommissionsField;
        
        private ServiceProviderAccount[] serviceAccountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("serviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string verifyServiceCode {
            get {
                return this.verifyServiceCodeField;
            }
            set {
                this.verifyServiceCodeField = value;
                this.RaisePropertyChanged("verifyServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string debtServiceCode {
            get {
                return this.debtServiceCodeField;
            }
            set {
                this.debtServiceCodeField = value;
                this.RaisePropertyChanged("debtServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string payServiceCode {
            get {
                return this.payServiceCodeField;
            }
            set {
                this.payServiceCodeField = value;
                this.RaisePropertyChanged("payServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cancelServiceCode {
            get {
                return this.cancelServiceCodeField;
            }
            set {
                this.cancelServiceCodeField = value;
                this.RaisePropertyChanged("cancelServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string abonentDetailsPattern {
            get {
                return this.abonentDetailsPatternField;
            }
            set {
                this.abonentDetailsPatternField = value;
                this.RaisePropertyChanged("abonentDetailsPattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool allAgentAccounts {
            get {
                return this.allAgentAccountsField;
            }
            set {
                this.allAgentAccountsField = value;
                this.RaisePropertyChanged("allAgentAccounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=9)]
        public byte[] serviceIcon {
            get {
                return this.serviceIconField;
            }
            set {
                this.serviceIconField = value;
                this.RaisePropertyChanged("serviceIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool oneTimePayment {
            get {
                return this.oneTimePaymentField;
            }
            set {
                this.oneTimePaymentField = value;
                this.RaisePropertyChanged("oneTimePayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool immediateTransaction {
            get {
                return this.immediateTransactionField;
            }
            set {
                this.immediateTransactionField = value;
                this.RaisePropertyChanged("immediateTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool transferCommissions {
            get {
                return this.transferCommissionsField;
            }
            set {
                this.transferCommissionsField = value;
                this.RaisePropertyChanged("transferCommissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool phoneAbonentCode {
            get {
                return this.phoneAbonentCodeField;
            }
            set {
                this.phoneAbonentCodeField = value;
                this.RaisePropertyChanged("phoneAbonentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceCommissions", Order=15)]
        public ServiceCommission[] serviceCommissions {
            get {
                return this.serviceCommissionsField;
            }
            set {
                this.serviceCommissionsField = value;
                this.RaisePropertyChanged("serviceCommissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceAccounts", IsNullable=true, Order=16)]
        public ServiceProviderAccount[] serviceAccounts {
            get {
                return this.serviceAccountsField;
            }
            set {
                this.serviceAccountsField = value;
                this.RaisePropertyChanged("serviceAccounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class ServiceProviderAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankCodeField;
        
        private string bankAccountNumberField;
        
        private string bankAccountNameField;
        
        private bool activeField;
        
        private TreasuryCode[] treasuryCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("bankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
                this.RaisePropertyChanged("bankAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bankAccountName {
            get {
                return this.bankAccountNameField;
            }
            set {
                this.bankAccountNameField = value;
                this.RaisePropertyChanged("bankAccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TreasuryCodes", Order=4)]
        public TreasuryCode[] TreasuryCodes {
            get {
                return this.treasuryCodesField;
            }
            set {
                this.treasuryCodesField = value;
                this.RaisePropertyChanged("TreasuryCodes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class TreasuryCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class ServiceProvider : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private string shortNameField;
        
        private string contactPersonField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string addressField;
        
        private string registrationCodeField;
        
        private ServiceProviderAccount[] serviceProviderAccountField;
        
        private Service[] serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("shortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string contactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
                this.RaisePropertyChanged("contactPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string registrationCode {
            get {
                return this.registrationCodeField;
            }
            set {
                this.registrationCodeField = value;
                this.RaisePropertyChanged("registrationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceProviderAccount", Order=9)]
        public ServiceProviderAccount[] ServiceProviderAccount {
            get {
                return this.serviceProviderAccountField;
            }
            set {
                this.serviceProviderAccountField = value;
                this.RaisePropertyChanged("ServiceProviderAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service", Order=10)]
        public Service[] Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class getServiceProvidersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceProvider[] serviceProvidersField;
        
        private UCCFault uccErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceProviders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ServiceProvider[] serviceProviders {
            get {
                return this.serviceProvidersField;
            }
            set {
                this.serviceProvidersField = value;
                this.RaisePropertyChanged("serviceProviders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UCCFault uccError {
            get {
                return this.uccErrorField;
            }
            set {
                this.uccErrorField = value;
                this.RaisePropertyChanged("uccError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class getServiceProviders : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class getPaymentsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Payment[] paymentsField;
        
        private UCCFault uccErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Payment[] payments {
            get {
                return this.paymentsField;
            }
            set {
                this.paymentsField = value;
                this.RaisePropertyChanged("payments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UCCFault uccError {
            get {
                return this.uccErrorField;
            }
            set {
                this.uccErrorField = value;
                this.RaisePropertyChanged("uccError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class Payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentIdField;
        
        private string agentPaymentIdField;
        
        private string serviceCodeField;
        
        private string serviceProviderCodeField;
        
        private string businessDayIdField;
        
        private float amountField;
        
        private float commissionField;
        
        private string currencyField;
        
        private string abonentCodeField;
        
        private System.DateTime paymentTimeField;
        
        private string paymentChannelField;
        
        private string paymentPointField;
        
        private string paymentPurposeField;
        
        private string additionalInfoField;
        
        private string payerNameField;
        
        private string payerIdentificationNumberField;
        
        private string treasuryCodeField;
        
        private paymentStatus statusField;
        
        private string clearingOrderDocumentNumberField;
        
        private string srcBankCodeField;
        
        private string srcBankAccountNumberField;
        
        private string destBankCodeField;
        
        private string destBankAccountNumberField;
        
        private string bankOrderDocumentNumberField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string paymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
                this.RaisePropertyChanged("paymentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agentPaymentId {
            get {
                return this.agentPaymentIdField;
            }
            set {
                this.agentPaymentIdField = value;
                this.RaisePropertyChanged("agentPaymentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("serviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string serviceProviderCode {
            get {
                return this.serviceProviderCodeField;
            }
            set {
                this.serviceProviderCodeField = value;
                this.RaisePropertyChanged("serviceProviderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string businessDayId {
            get {
                return this.businessDayIdField;
            }
            set {
                this.businessDayIdField = value;
                this.RaisePropertyChanged("businessDayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string abonentCode {
            get {
                return this.abonentCodeField;
            }
            set {
                this.abonentCodeField = value;
                this.RaisePropertyChanged("abonentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime paymentTime {
            get {
                return this.paymentTimeField;
            }
            set {
                this.paymentTimeField = value;
                this.RaisePropertyChanged("paymentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string paymentChannel {
            get {
                return this.paymentChannelField;
            }
            set {
                this.paymentChannelField = value;
                this.RaisePropertyChanged("paymentChannel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string paymentPoint {
            get {
                return this.paymentPointField;
            }
            set {
                this.paymentPointField = value;
                this.RaisePropertyChanged("paymentPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string paymentPurpose {
            get {
                return this.paymentPurposeField;
            }
            set {
                this.paymentPurposeField = value;
                this.RaisePropertyChanged("paymentPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string payerName {
            get {
                return this.payerNameField;
            }
            set {
                this.payerNameField = value;
                this.RaisePropertyChanged("payerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string payerIdentificationNumber {
            get {
                return this.payerIdentificationNumberField;
            }
            set {
                this.payerIdentificationNumberField = value;
                this.RaisePropertyChanged("payerIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string treasuryCode {
            get {
                return this.treasuryCodeField;
            }
            set {
                this.treasuryCodeField = value;
                this.RaisePropertyChanged("treasuryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public paymentStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string clearingOrderDocumentNumber {
            get {
                return this.clearingOrderDocumentNumberField;
            }
            set {
                this.clearingOrderDocumentNumberField = value;
                this.RaisePropertyChanged("clearingOrderDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string srcBankCode {
            get {
                return this.srcBankCodeField;
            }
            set {
                this.srcBankCodeField = value;
                this.RaisePropertyChanged("srcBankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string srcBankAccountNumber {
            get {
                return this.srcBankAccountNumberField;
            }
            set {
                this.srcBankAccountNumberField = value;
                this.RaisePropertyChanged("srcBankAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string destBankCode {
            get {
                return this.destBankCodeField;
            }
            set {
                this.destBankCodeField = value;
                this.RaisePropertyChanged("destBankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string destBankAccountNumber {
            get {
                return this.destBankAccountNumberField;
            }
            set {
                this.destBankAccountNumberField = value;
                this.RaisePropertyChanged("destBankAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string bankOrderDocumentNumber {
            get {
                return this.bankOrderDocumentNumberField;
            }
            set {
                this.bankOrderDocumentNumberField = value;
                this.RaisePropertyChanged("bankOrderDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public enum paymentStatus {
        
        /// <remarks/>
        PERFORMING,
        
        /// <remarks/>
        ENQUEUED,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        PERFORMED,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        CANCELLING,
        
        /// <remarks/>
        CANCELED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
    public partial class getPaymentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Payment paymentField;
        
        private UCCFault uccErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Payment payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UCCFault uccError {
            get {
                return this.uccErrorField;
            }
            set {
                this.uccErrorField = value;
                this.RaisePropertyChanged("uccError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WinFormsTest.ucc.getPayment getPayment;
        
        public getPaymentRequest() {
        }
        
        public getPaymentRequest(WinFormsTest.ucc.getPayment getPayment) {
            this.getPayment = getPayment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.getPaymentResponse getPaymentResponse;
        
        public getPaymentResponse1() {
        }
        
        public getPaymentResponse1(WinFormsTest.ucc.getPaymentResponse getPaymentResponse) {
            this.getPaymentResponse = getPaymentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
    public partial class getPayments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessDayIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessDayId {
            get {
                return this.businessDayIdField;
            }
            set {
                this.businessDayIdField = value;
                this.RaisePropertyChanged("businessDayId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WinFormsTest.ucc.getPayments getPayments;
        
        public getPaymentsRequest() {
        }
        
        public getPaymentsRequest(WinFormsTest.ucc.getPayments getPayments) {
            this.getPayments = getPayments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.getPaymentsResponse getPaymentsResponse;
        
        public getPaymentsResponse1() {
        }
        
        public getPaymentsResponse1(WinFormsTest.ucc.getPaymentsResponse getPaymentsResponse) {
            this.getPaymentsResponse = getPaymentsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceProvidersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.getServiceProviders getServiceProviders;
        
        public getServiceProvidersRequest() {
        }
        
        public getServiceProvidersRequest(WinFormsTest.ucc.getServiceProviders getServiceProviders) {
            this.getServiceProviders = getServiceProviders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceProvidersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.getServiceProvidersResponse getServiceProvidersResponse;
        
        public getServiceProvidersResponse1() {
        }
        
        public getServiceProvidersResponse1(WinFormsTest.ucc.getServiceProvidersResponse getServiceProvidersResponse) {
            this.getServiceProvidersResponse = getServiceProvidersResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
    public partial class reconcile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessDayIdField;
        
        private float paymentsAmountField;
        
        private int paymentsNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessDayId {
            get {
                return this.businessDayIdField;
            }
            set {
                this.businessDayIdField = value;
                this.RaisePropertyChanged("businessDayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float paymentsAmount {
            get {
                return this.paymentsAmountField;
            }
            set {
                this.paymentsAmountField = value;
                this.RaisePropertyChanged("paymentsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int paymentsNumber {
            get {
                return this.paymentsNumberField;
            }
            set {
                this.paymentsNumberField = value;
                this.RaisePropertyChanged("paymentsNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reconcileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WinFormsTest.ucc.reconcile reconcile;
        
        public reconcileRequest() {
        }
        
        public reconcileRequest(WinFormsTest.ucc.reconcile reconcile) {
            this.reconcile = reconcile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reconcileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.reconcileResponse reconcileResponse;
        
        public reconcileResponse1() {
        }
        
        public reconcileResponse1(WinFormsTest.ucc.reconcileResponse reconcileResponse) {
            this.reconcileResponse = reconcileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
    public partial class registerClearingOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClearingOrder clearingOrderField;
        
        private string[] paymentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ClearingOrder clearingOrder {
            get {
                return this.clearingOrderField;
            }
            set {
                this.clearingOrderField = value;
                this.RaisePropertyChanged("clearingOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] paymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
                this.RaisePropertyChanged("paymentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerClearingOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WinFormsTest.ucc.registerClearingOrder registerClearingOrder;
        
        public registerClearingOrderRequest() {
        }
        
        public registerClearingOrderRequest(WinFormsTest.ucc.registerClearingOrder registerClearingOrder) {
            this.registerClearingOrder = registerClearingOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerClearingOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
        public WinFormsTest.ucc.registerClearingOrderResponse registerClearingOrderResponse;
        
        public registerClearingOrderResponse1() {
        }
        
        public registerClearingOrderResponse1(WinFormsTest.ucc.registerClearingOrderResponse registerClearingOrderResponse) {
            this.registerClearingOrderResponse = registerClearingOrderResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UCCServicesWCFChannel : WinFormsTest.ucc.UCCServicesWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UCCServicesWCFClient : System.ServiceModel.ClientBase<WinFormsTest.ucc.UCCServicesWCF>, WinFormsTest.ucc.UCCServicesWCF {
        
        public UCCServicesWCFClient() {
        }
        
        public UCCServicesWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UCCServicesWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCCServicesWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCCServicesWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.ucc.getPaymentResponse1 WinFormsTest.ucc.UCCServicesWCF.getPayment(WinFormsTest.ucc.getPaymentRequest request) {
            return base.Channel.getPayment(request);
        }
        
        public WinFormsTest.ucc.getPaymentResponse getPayment(WinFormsTest.ucc.getPayment getPayment1) {
            WinFormsTest.ucc.getPaymentRequest inValue = new WinFormsTest.ucc.getPaymentRequest();
            inValue.getPayment = getPayment1;
            WinFormsTest.ucc.getPaymentResponse1 retVal = ((WinFormsTest.ucc.UCCServicesWCF)(this)).getPayment(inValue);
            return retVal.getPaymentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.ucc.getPaymentsResponse1 WinFormsTest.ucc.UCCServicesWCF.getPayments(WinFormsTest.ucc.getPaymentsRequest request) {
            return base.Channel.getPayments(request);
        }
        
        public WinFormsTest.ucc.getPaymentsResponse getPayments(WinFormsTest.ucc.getPayments getPayments1) {
            WinFormsTest.ucc.getPaymentsRequest inValue = new WinFormsTest.ucc.getPaymentsRequest();
            inValue.getPayments = getPayments1;
            WinFormsTest.ucc.getPaymentsResponse1 retVal = ((WinFormsTest.ucc.UCCServicesWCF)(this)).getPayments(inValue);
            return retVal.getPaymentsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.ucc.getServiceProvidersResponse1 WinFormsTest.ucc.UCCServicesWCF.getServiceProviders(WinFormsTest.ucc.getServiceProvidersRequest request) {
            return base.Channel.getServiceProviders(request);
        }
        
        public WinFormsTest.ucc.getServiceProvidersResponse getServiceProviders(WinFormsTest.ucc.getServiceProviders getServiceProviders1) {
            WinFormsTest.ucc.getServiceProvidersRequest inValue = new WinFormsTest.ucc.getServiceProvidersRequest();
            inValue.getServiceProviders = getServiceProviders1;
            WinFormsTest.ucc.getServiceProvidersResponse1 retVal = ((WinFormsTest.ucc.UCCServicesWCF)(this)).getServiceProviders(inValue);
            return retVal.getServiceProvidersResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.ucc.reconcileResponse1 WinFormsTest.ucc.UCCServicesWCF.reconcile(WinFormsTest.ucc.reconcileRequest request) {
            return base.Channel.reconcile(request);
        }
        
        public WinFormsTest.ucc.reconcileResponse reconcile(WinFormsTest.ucc.reconcile reconcile1) {
            WinFormsTest.ucc.reconcileRequest inValue = new WinFormsTest.ucc.reconcileRequest();
            inValue.reconcile = reconcile1;
            WinFormsTest.ucc.reconcileResponse1 retVal = ((WinFormsTest.ucc.UCCServicesWCF)(this)).reconcile(inValue);
            return retVal.reconcileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.ucc.registerClearingOrderResponse1 WinFormsTest.ucc.UCCServicesWCF.registerClearingOrder(WinFormsTest.ucc.registerClearingOrderRequest request) {
            return base.Channel.registerClearingOrder(request);
        }
        
        public WinFormsTest.ucc.registerClearingOrderResponse registerClearingOrder(WinFormsTest.ucc.registerClearingOrder registerClearingOrder1) {
            WinFormsTest.ucc.registerClearingOrderRequest inValue = new WinFormsTest.ucc.registerClearingOrderRequest();
            inValue.registerClearingOrder = registerClearingOrder1;
            WinFormsTest.ucc.registerClearingOrderResponse1 retVal = ((WinFormsTest.ucc.UCCServicesWCF)(this)).registerClearingOrder(inValue);
            return retVal.registerClearingOrderResponse;
        }
    }
}
