//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsTest.nci {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nci.connector.ess.azry.com/", ConfigurationName="nci.NCIServiceWCF")]
    internal interface NCIServiceWCF {
        
        // CODEGEN: Generating message contract since the operation bulkExecute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:bulkExecuteWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.nci.bulkExecuteResponse bulkExecute(WinFormsTest.nci.bulkExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:executeWCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WinFormsTest.nci.executeResponse1 execute(WinFormsTest.nci.executeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class ExecuteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIdField;
        
        private Parameter[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class Parameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class executeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Parameter[] outParameterField;
        
        private FaultEntry[] faultEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outParameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Parameter[] outParameter {
            get {
                return this.outParameterField;
            }
            set {
                this.outParameterField = value;
                this.RaisePropertyChanged("outParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultEntry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FaultEntry[] faultEntry {
            get {
                return this.faultEntryField;
            }
            set {
                this.faultEntryField = value;
                this.RaisePropertyChanged("faultEntry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class FaultEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorKeyField;
        
        private string[] errorParametersField;
        
        private string invalidParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorKey {
            get {
                return this.errorKeyField;
            }
            set {
                this.errorKeyField = value;
                this.RaisePropertyChanged("errorKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter")]
        public string[] errorParameters {
            get {
                return this.errorParametersField;
            }
            set {
                this.errorParametersField = value;
                this.RaisePropertyChanged("errorParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string invalidParameter {
            get {
                return this.invalidParameterField;
            }
            set {
                this.invalidParameterField = value;
                this.RaisePropertyChanged("invalidParameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class execute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIdField;
        
        private Parameter[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
    public partial class ExecuteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Parameter[] parameterField;
        
        private FaultEntry[] faultEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultEntries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public FaultEntry[] faultEntries {
            get {
                return this.faultEntriesField;
            }
            set {
                this.faultEntriesField = value;
                this.RaisePropertyChanged("faultEntries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bulkExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("executeRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ExecuteRequest[] bulkExecute;
        
        public bulkExecuteRequest() {
        }
        
        public bulkExecuteRequest(ExecuteRequest[] bulkExecute) {
            this.bulkExecute = bulkExecute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bulkExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bulkExecuteResponse", Namespace="http://nci.connector.ess.azry.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ExecuteResult[] bulkExecuteResponse1;
        
        public bulkExecuteResponse() {
        }
        
        public bulkExecuteResponse(ExecuteResult[] bulkExecuteResponse1) {
            this.bulkExecuteResponse1 = bulkExecuteResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class executeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
        public WinFormsTest.nci.execute execute;
        
        public executeRequest1() {
        }
        
        public executeRequest1(WinFormsTest.nci.execute execute) {
            this.execute = execute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class executeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
        public WinFormsTest.nci.executeResponse executeResponse;
        
        public executeResponse1() {
        }
        
        public executeResponse1(WinFormsTest.nci.executeResponse executeResponse) {
            this.executeResponse = executeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface NCIServiceWCFChannel : WinFormsTest.nci.NCIServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class NCIServiceWCFClient : System.ServiceModel.ClientBase<WinFormsTest.nci.NCIServiceWCF>, WinFormsTest.nci.NCIServiceWCF {
        
        public NCIServiceWCFClient() {
        }
        
        public NCIServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NCIServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCIServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCIServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.nci.bulkExecuteResponse WinFormsTest.nci.NCIServiceWCF.bulkExecute(WinFormsTest.nci.bulkExecuteRequest request) {
            return base.Channel.bulkExecute(request);
        }
        
        public ExecuteResult[] bulkExecute(ExecuteRequest[] bulkExecute1) {
            WinFormsTest.nci.bulkExecuteRequest inValue = new WinFormsTest.nci.bulkExecuteRequest();
            inValue.bulkExecute = bulkExecute1;
            WinFormsTest.nci.bulkExecuteResponse retVal = ((WinFormsTest.nci.NCIServiceWCF)(this)).bulkExecute(inValue);
            return retVal.bulkExecuteResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsTest.nci.executeResponse1 WinFormsTest.nci.NCIServiceWCF.execute(WinFormsTest.nci.executeRequest1 request) {
            return base.Channel.execute(request);
        }
        
        public WinFormsTest.nci.executeResponse execute(WinFormsTest.nci.execute execute1) {
            WinFormsTest.nci.executeRequest1 inValue = new WinFormsTest.nci.executeRequest1();
            inValue.execute = execute1;
            WinFormsTest.nci.executeResponse1 retVal = ((WinFormsTest.nci.NCIServiceWCF)(this)).execute(inValue);
            return retVal.executeResponse;
        }
    }
}
