//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://nci.connector.ess.azry.com/", ConfigurationName="NCIServiceWCF")]
public interface NCIServiceWCF
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:execute")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    executeResponse execute(execute request);
    
    // CODEGEN: Parameter 'ExecuteResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="urn:bulkExecute")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="ExecuteResult")]
    bulkExecuteResponse bulkExecute(bulkExecute request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
public partial class Parameter
{
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
public partial class ExecuteResult
{
    
    private Parameter[] parameterField;
    
    private FaultEntry[] faultEntriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public Parameter[] parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("faultEntries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public FaultEntry[] faultEntries
    {
        get
        {
            return this.faultEntriesField;
        }
        set
        {
            this.faultEntriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
public partial class FaultEntry
{
    
    private string errorKeyField;
    
    private string[] errorParametersField;
    
    private string invalidParameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string errorKey
    {
        get
        {
            return this.errorKeyField;
        }
        set
        {
            this.errorKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("parameter")]
    public string[] errorParameters
    {
        get
        {
            return this.errorParametersField;
        }
        set
        {
            this.errorParametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string invalidParameter
    {
        get
        {
            return this.invalidParameterField;
        }
        set
        {
            this.invalidParameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nci.connector.ess.azry.com/")]
public partial class ExecuteRequest
{
    
    private string serviceIdField;
    
    private Parameter[] parameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string serviceId
    {
        get
        {
            return this.serviceIdField;
        }
        set
        {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public Parameter[] parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://nci.connector.ess.azry.com/", IsWrapped=true)]
public partial class execute
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Parameter[] parameter;
    
    public execute()
    {
    }
    
    public execute(string serviceId, Parameter[] parameter)
    {
        this.serviceId = serviceId;
        this.parameter = parameter;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://nci.connector.ess.azry.com/", IsWrapped=true)]
public partial class executeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("outParameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Parameter[] outParameter;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("faultEntry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public FaultEntry[] faultEntry;
    
    public executeResponse()
    {
    }
    
    public executeResponse(Parameter[] outParameter, FaultEntry[] faultEntry)
    {
        this.outParameter = outParameter;
        this.faultEntry = faultEntry;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="bulkExecute", WrapperNamespace="http://nci.connector.ess.azry.com/", IsWrapped=true)]
public partial class bulkExecute
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("executeRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExecuteRequest[] executeRequest;
    
    public bulkExecute()
    {
    }
    
    public bulkExecute(ExecuteRequest[] executeRequest)
    {
        this.executeRequest = executeRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="bulkExecuteResponse", WrapperNamespace="http://nci.connector.ess.azry.com/", IsWrapped=true)]
public partial class bulkExecuteResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nci.connector.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ExecuteResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExecuteResult[] ExecuteResult;
    
    public bulkExecuteResponse()
    {
    }
    
    public bulkExecuteResponse(ExecuteResult[] ExecuteResult)
    {
        this.ExecuteResult = ExecuteResult;
    }
}
