//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://ucc.ess.azry.com/", ClrNamespace="ucc.ess.azry.com")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ucc.ess.azry.com/", ConfigurationName="UCCServices")]
public interface UCCServices
{
    
    // CODEGEN: Generating message contract since the operation getCommission is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getCommission")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:getCommission", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getCommissionResponse1 getCommission(getCommissionRequest request);
    
    // CODEGEN: Generating message contract since the operation getPayment is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getPayment")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:getPayment", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getPaymentResponse1 getPayment(getPaymentRequest request);
    
    // CODEGEN: Generating message contract since the operation getPayments is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getPayments")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:getPayments", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getPaymentsResponse getPayments(getPaymentsRequest request);
    
    // CODEGEN: Generating message contract since the operation getServiceProviders is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getServiceProvider")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:getServiceProvider", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getServiceProvidersResponse getServiceProviders(getServiceProvidersRequest request);
    
    // CODEGEN: Generating message contract since the operation reconcile is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:reconcile")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:reconcile", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    reconcileResponse1 reconcile(reconcileRequest request);
    
    // CODEGEN: Generating message contract since the operation registerClearingOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:registerClearingOrder")]
    [System.ServiceModel.FaultContractAttribute(typeof(ucc.ess.azry.com.UCCFault), Action="urn:registerClearingOrder", Name="UCCFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    registerClearingOrderResponse1 registerClearingOrder(registerClearingOrderRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class getCommission
{
    
    private float amountField;
    
    private string currencyField;
    
    private string serviceCodeField;
    
    private string paymentChannelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public float amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string serviceCode
    {
        get
        {
            return this.serviceCodeField;
        }
        set
        {
            this.serviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string paymentChannel
    {
        get
        {
            return this.paymentChannelField;
        }
        set
        {
            this.paymentChannelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class registerClearingOrderResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class ClearingOrder
{
    
    private string bankOrderDocumentNumberField;
    
    private string serviceProviderCodeField;
    
    private float amountField;
    
    private string currencyField;
    
    private string paymentPurposeField;
    
    private string additionalInfoField;
    
    private string payerNameField;
    
    private string payerIdentificationNumberField;
    
    private string treasuryCodeField;
    
    private System.DateTime clearingTimeField;
    
    private string receiverBankCodeField;
    
    private string receiverBankAccountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string bankOrderDocumentNumber
    {
        get
        {
            return this.bankOrderDocumentNumberField;
        }
        set
        {
            this.bankOrderDocumentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string serviceProviderCode
    {
        get
        {
            return this.serviceProviderCodeField;
        }
        set
        {
            this.serviceProviderCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public float amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string paymentPurpose
    {
        get
        {
            return this.paymentPurposeField;
        }
        set
        {
            this.paymentPurposeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string additionalInfo
    {
        get
        {
            return this.additionalInfoField;
        }
        set
        {
            this.additionalInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string payerName
    {
        get
        {
            return this.payerNameField;
        }
        set
        {
            this.payerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string payerIdentificationNumber
    {
        get
        {
            return this.payerIdentificationNumberField;
        }
        set
        {
            this.payerIdentificationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string treasuryCode
    {
        get
        {
            return this.treasuryCodeField;
        }
        set
        {
            this.treasuryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public System.DateTime clearingTime
    {
        get
        {
            return this.clearingTimeField;
        }
        set
        {
            this.clearingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string receiverBankCode
    {
        get
        {
            return this.receiverBankCodeField;
        }
        set
        {
            this.receiverBankCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string receiverBankAccount
    {
        get
        {
            return this.receiverBankAccountField;
        }
        set
        {
            this.receiverBankAccountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class ReconcilationResult
{
    
    private BusinessDayStatus businessDayStatusField;
    
    private float expectedPaymentsAmountField;
    
    private int expectedPaymentsNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BusinessDayStatus businessDayStatus
    {
        get
        {
            return this.businessDayStatusField;
        }
        set
        {
            this.businessDayStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float expectedPaymentsAmount
    {
        get
        {
            return this.expectedPaymentsAmountField;
        }
        set
        {
            this.expectedPaymentsAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int expectedPaymentsNumber
    {
        get
        {
            return this.expectedPaymentsNumberField;
        }
        set
        {
            this.expectedPaymentsNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public enum BusinessDayStatus
{
    
    /// <remarks/>
    OPENED,
    
    /// <remarks/>
    CLOSED_NORMAL,
    
    /// <remarks/>
    CLOSED_IRREGULAR,
    
    /// <remarks/>
    CLOSED_AFTER_REVISION,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class reconcileResponse
{
    
    private ReconcilationResult reconcilationResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public ReconcilationResult ReconcilationResult
    {
        get
        {
            return this.reconcilationResultField;
        }
        set
        {
            this.reconcilationResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class ServiceCommission
{
    
    private float minAmountField;
    
    private float maxAmountField;
    
    private string currencyField;
    
    private string serviceConsumerCodeField;
    
    private string paymentChannelField;
    
    private float commissionFixedField;
    
    private float commissionPercentField;
    
    private float minCommissionField;
    
    private float maxCommissionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float minAmount
    {
        get
        {
            return this.minAmountField;
        }
        set
        {
            this.minAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float maxAmount
    {
        get
        {
            return this.maxAmountField;
        }
        set
        {
            this.maxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string serviceConsumerCode
    {
        get
        {
            return this.serviceConsumerCodeField;
        }
        set
        {
            this.serviceConsumerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string paymentChannel
    {
        get
        {
            return this.paymentChannelField;
        }
        set
        {
            this.paymentChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public float commissionFixed
    {
        get
        {
            return this.commissionFixedField;
        }
        set
        {
            this.commissionFixedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public float commissionPercent
    {
        get
        {
            return this.commissionPercentField;
        }
        set
        {
            this.commissionPercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public float minCommission
    {
        get
        {
            return this.minCommissionField;
        }
        set
        {
            this.minCommissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public float maxCommission
    {
        get
        {
            return this.maxCommissionField;
        }
        set
        {
            this.maxCommissionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class Service
{
    
    private string serviceCodeField;
    
    private string descriptionField;
    
    private string verifyServiceCodeField;
    
    private string debtServiceCodeField;
    
    private string payServiceCodeField;
    
    private string cancelServiceCodeField;
    
    private string abonentDetailsPatternField;
    
    private bool activeField;
    
    private bool allAgentAccountsField;
    
    private byte[] serviceIconField;
    
    private bool oneTimePaymentField;
    
    private bool immediateTransactionField;
    
    private bool additionalInfoField;
    
    private bool transferCommissionsField;
    
    private bool phoneAbonentCodeField;
    
    private ServiceCommission[] serviceCommissionsField;
    
    private ServiceProviderAccount[] serviceAccountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string serviceCode
    {
        get
        {
            return this.serviceCodeField;
        }
        set
        {
            this.serviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string verifyServiceCode
    {
        get
        {
            return this.verifyServiceCodeField;
        }
        set
        {
            this.verifyServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string debtServiceCode
    {
        get
        {
            return this.debtServiceCodeField;
        }
        set
        {
            this.debtServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string payServiceCode
    {
        get
        {
            return this.payServiceCodeField;
        }
        set
        {
            this.payServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string cancelServiceCode
    {
        get
        {
            return this.cancelServiceCodeField;
        }
        set
        {
            this.cancelServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string abonentDetailsPattern
    {
        get
        {
            return this.abonentDetailsPatternField;
        }
        set
        {
            this.abonentDetailsPatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool allAgentAccounts
    {
        get
        {
            return this.allAgentAccountsField;
        }
        set
        {
            this.allAgentAccountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=9)]
    public byte[] serviceIcon
    {
        get
        {
            return this.serviceIconField;
        }
        set
        {
            this.serviceIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public bool oneTimePayment
    {
        get
        {
            return this.oneTimePaymentField;
        }
        set
        {
            this.oneTimePaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public bool immediateTransaction
    {
        get
        {
            return this.immediateTransactionField;
        }
        set
        {
            this.immediateTransactionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public bool additionalInfo
    {
        get
        {
            return this.additionalInfoField;
        }
        set
        {
            this.additionalInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public bool transferCommissions
    {
        get
        {
            return this.transferCommissionsField;
        }
        set
        {
            this.transferCommissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public bool phoneAbonentCode
    {
        get
        {
            return this.phoneAbonentCodeField;
        }
        set
        {
            this.phoneAbonentCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serviceCommissions", Order=15)]
    public ServiceCommission[] serviceCommissions
    {
        get
        {
            return this.serviceCommissionsField;
        }
        set
        {
            this.serviceCommissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serviceAccounts", IsNullable=true, Order=16)]
    public ServiceProviderAccount[] serviceAccounts
    {
        get
        {
            return this.serviceAccountsField;
        }
        set
        {
            this.serviceAccountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class ServiceProviderAccount
{
    
    private string bankCodeField;
    
    private string bankAccountNumberField;
    
    private string bankAccountNameField;
    
    private bool activeField;
    
    private TreasuryCode[] treasuryCodesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string bankCode
    {
        get
        {
            return this.bankCodeField;
        }
        set
        {
            this.bankCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string bankAccountNumber
    {
        get
        {
            return this.bankAccountNumberField;
        }
        set
        {
            this.bankAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string bankAccountName
    {
        get
        {
            return this.bankAccountNameField;
        }
        set
        {
            this.bankAccountNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TreasuryCodes", Order=4)]
    public TreasuryCode[] TreasuryCodes
    {
        get
        {
            return this.treasuryCodesField;
        }
        set
        {
            this.treasuryCodesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class TreasuryCode
{
    
    private string codeField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class ServiceProvider
{
    
    private string codeField;
    
    private string nameField;
    
    private string shortNameField;
    
    private string contactPersonField;
    
    private string phoneField;
    
    private string faxField;
    
    private string emailField;
    
    private string addressField;
    
    private string registrationCodeField;
    
    private ServiceProviderAccount[] serviceProviderAccountField;
    
    private Service[] serviceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string shortName
    {
        get
        {
            return this.shortNameField;
        }
        set
        {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string contactPerson
    {
        get
        {
            return this.contactPersonField;
        }
        set
        {
            this.contactPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string fax
    {
        get
        {
            return this.faxField;
        }
        set
        {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string registrationCode
    {
        get
        {
            return this.registrationCodeField;
        }
        set
        {
            this.registrationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceProviderAccount", Order=9)]
    public ServiceProviderAccount[] ServiceProviderAccount
    {
        get
        {
            return this.serviceProviderAccountField;
        }
        set
        {
            this.serviceProviderAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Service", Order=10)]
    public Service[] Service
    {
        get
        {
            return this.serviceField;
        }
        set
        {
            this.serviceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class getServiceProviders
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class Payment
{
    
    private string paymentIdField;
    
    private string agentPaymentIdField;
    
    private string serviceCodeField;
    
    private string serviceProviderCodeField;
    
    private string businessDayIdField;
    
    private float amountField;
    
    private float commissionField;
    
    private string currencyField;
    
    private string abonentCodeField;
    
    private System.DateTime paymentTimeField;
    
    private string paymentChannelField;
    
    private string paymentPointField;
    
    private string paymentPurposeField;
    
    private string additionalInfoField;
    
    private string payerNameField;
    
    private string payerIdentificationNumberField;
    
    private string treasuryCodeField;
    
    private paymentStatus statusField;
    
    private string clearingOrderDocumentNumberField;
    
    private string srcBankCodeField;
    
    private string srcBankAccountNumberField;
    
    private string destBankCodeField;
    
    private string destBankAccountNumberField;
    
    private string bankOrderDocumentNumberField;
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string paymentId
    {
        get
        {
            return this.paymentIdField;
        }
        set
        {
            this.paymentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string agentPaymentId
    {
        get
        {
            return this.agentPaymentIdField;
        }
        set
        {
            this.agentPaymentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string serviceCode
    {
        get
        {
            return this.serviceCodeField;
        }
        set
        {
            this.serviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string serviceProviderCode
    {
        get
        {
            return this.serviceProviderCodeField;
        }
        set
        {
            this.serviceProviderCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string businessDayId
    {
        get
        {
            return this.businessDayIdField;
        }
        set
        {
            this.businessDayIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public float amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public float commission
    {
        get
        {
            return this.commissionField;
        }
        set
        {
            this.commissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string abonentCode
    {
        get
        {
            return this.abonentCodeField;
        }
        set
        {
            this.abonentCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public System.DateTime paymentTime
    {
        get
        {
            return this.paymentTimeField;
        }
        set
        {
            this.paymentTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string paymentChannel
    {
        get
        {
            return this.paymentChannelField;
        }
        set
        {
            this.paymentChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string paymentPoint
    {
        get
        {
            return this.paymentPointField;
        }
        set
        {
            this.paymentPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string paymentPurpose
    {
        get
        {
            return this.paymentPurposeField;
        }
        set
        {
            this.paymentPurposeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public string additionalInfo
    {
        get
        {
            return this.additionalInfoField;
        }
        set
        {
            this.additionalInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public string payerName
    {
        get
        {
            return this.payerNameField;
        }
        set
        {
            this.payerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public string payerIdentificationNumber
    {
        get
        {
            return this.payerIdentificationNumberField;
        }
        set
        {
            this.payerIdentificationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public string treasuryCode
    {
        get
        {
            return this.treasuryCodeField;
        }
        set
        {
            this.treasuryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public paymentStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
    public string clearingOrderDocumentNumber
    {
        get
        {
            return this.clearingOrderDocumentNumberField;
        }
        set
        {
            this.clearingOrderDocumentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public string srcBankCode
    {
        get
        {
            return this.srcBankCodeField;
        }
        set
        {
            this.srcBankCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public string srcBankAccountNumber
    {
        get
        {
            return this.srcBankAccountNumberField;
        }
        set
        {
            this.srcBankAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public string destBankCode
    {
        get
        {
            return this.destBankCodeField;
        }
        set
        {
            this.destBankCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public string destBankAccountNumber
    {
        get
        {
            return this.destBankAccountNumberField;
        }
        set
        {
            this.destBankAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public string bankOrderDocumentNumber
    {
        get
        {
            return this.bankOrderDocumentNumberField;
        }
        set
        {
            this.bankOrderDocumentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public string errorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public enum paymentStatus
{
    
    /// <remarks/>
    PERFORMING,
    
    /// <remarks/>
    ENQUEUED,
    
    /// <remarks/>
    PENDING,
    
    /// <remarks/>
    PERFORMED,
    
    /// <remarks/>
    REJECTED,
    
    /// <remarks/>
    FAILED,
    
    /// <remarks/>
    CANCELLING,
    
    /// <remarks/>
    CANCELED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class getPaymentResponse
{
    
    private Payment paymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public Payment Payment
    {
        get
        {
            return this.paymentField;
        }
        set
        {
            this.paymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucc.ess.azry.com/")]
public partial class getCommissionResponse
{
    
    private float commissionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public float Commission
    {
        get
        {
            return this.commissionField;
        }
        set
        {
            this.commissionField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getCommissionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public getCommission getCommission;
    
    public getCommissionRequest()
    {
    }
    
    public getCommissionRequest(getCommission getCommission)
    {
        this.getCommission = getCommission;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getCommissionResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public getCommissionResponse getCommissionResponse;
    
    public getCommissionResponse1()
    {
    }
    
    public getCommissionResponse1(getCommissionResponse getCommissionResponse)
    {
        this.getCommissionResponse = getCommissionResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
public partial class getPayment
{
    
    private string paymentIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string paymentId
    {
        get
        {
            return this.paymentIdField;
        }
        set
        {
            this.paymentIdField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getPaymentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public getPayment getPayment;
    
    public getPaymentRequest()
    {
    }
    
    public getPaymentRequest(getPayment getPayment)
    {
        this.getPayment = getPayment;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getPaymentResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public getPaymentResponse getPaymentResponse;
    
    public getPaymentResponse1()
    {
    }
    
    public getPaymentResponse1(getPaymentResponse getPaymentResponse)
    {
        this.getPaymentResponse = getPaymentResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
public partial class getPayments
{
    
    private string businessDayIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string businessDayId
    {
        get
        {
            return this.businessDayIdField;
        }
        set
        {
            this.businessDayIdField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getPaymentsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public getPayments getPayments;
    
    public getPaymentsRequest()
    {
    }
    
    public getPaymentsRequest(getPayments getPayments)
    {
        this.getPayments = getPayments;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getPaymentsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentsResponse", Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Payment[] getPaymentsResponse1;
    
    public getPaymentsResponse()
    {
    }
    
    public getPaymentsResponse(Payment[] getPaymentsResponse1)
    {
        this.getPaymentsResponse1 = getPaymentsResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getServiceProvidersRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public getServiceProviders getServiceProviders;
    
    public getServiceProvidersRequest()
    {
    }
    
    public getServiceProvidersRequest(getServiceProviders getServiceProviders)
    {
        this.getServiceProviders = getServiceProviders;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getServiceProvidersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceProvidersResponse", Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ServiceProviders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ServiceProvider[] getServiceProvidersResponse1;
    
    public getServiceProvidersResponse()
    {
    }
    
    public getServiceProvidersResponse(ServiceProvider[] getServiceProvidersResponse1)
    {
        this.getServiceProvidersResponse1 = getServiceProvidersResponse1;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
public partial class reconcile
{
    
    private string businessDayIdField;
    
    private float paymentsAmountField;
    
    private int paymentsNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string businessDayId
    {
        get
        {
            return this.businessDayIdField;
        }
        set
        {
            this.businessDayIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public float paymentsAmount
    {
        get
        {
            return this.paymentsAmountField;
        }
        set
        {
            this.paymentsAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int paymentsNumber
    {
        get
        {
            return this.paymentsNumberField;
        }
        set
        {
            this.paymentsNumberField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class reconcileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public reconcile reconcile;
    
    public reconcileRequest()
    {
    }
    
    public reconcileRequest(reconcile reconcile)
    {
        this.reconcile = reconcile;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class reconcileResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public reconcileResponse reconcileResponse;
    
    public reconcileResponse1()
    {
    }
    
    public reconcileResponse1(reconcileResponse reconcileResponse)
    {
        this.reconcileResponse = reconcileResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ucc.ess.azry.com/")]
public partial class registerClearingOrder
{
    
    private ClearingOrder clearingOrderField;
    
    private string[] paymentIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public ClearingOrder clearingOrder
    {
        get
        {
            return this.clearingOrderField;
        }
        set
        {
            this.clearingOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paymentId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string[] paymentId
    {
        get
        {
            return this.paymentIdField;
        }
        set
        {
            this.paymentIdField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class registerClearingOrderRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public registerClearingOrder registerClearingOrder;
    
    public registerClearingOrderRequest()
    {
    }
    
    public registerClearingOrderRequest(registerClearingOrder registerClearingOrder)
    {
        this.registerClearingOrder = registerClearingOrder;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class registerClearingOrderResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ucc.ess.azry.com/", Order=0)]
    public registerClearingOrderResponse registerClearingOrderResponse;
    
    public registerClearingOrderResponse1()
    {
    }
    
    public registerClearingOrderResponse1(registerClearingOrderResponse registerClearingOrderResponse)
    {
        this.registerClearingOrderResponse = registerClearingOrderResponse;
    }
}
namespace ucc.ess.azry.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UCCFault", Namespace="http://ucc.ess.azry.com/")]
    public partial class UCCFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ucc.ess.azry.com.UCCError errorCodeField;
        
        private string errorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ucc.ess.azry.com.UCCError errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UCCError", Namespace="http://ucc.ess.azry.com/")]
    public enum UCCError : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYSTEM_INTERNAL_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN_BUSINESS_DAY = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN_SERVICE_PROVIDER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN_PAYMENT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN_SERVICE = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILLEGAL_CLEARING_PAYMENT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILLEGAL_CLEARING_CURRENCY = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILLEGAL_CLEARING_SP_CODE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_CLEARING_AMOUNT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_UNIQUE_BANK_ORDER_NUMBER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_UNIQUE_AGENT_PAYMENT_ID = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_UNIQUE_BUSINESS_DAY_ID = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMMISSION_CALCULATION_ERROR = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_CANCEL_AMOUNT = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_CANCEL_CURRENCY = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_CANCELLING = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_ALREADY_CANCELED = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_FAILED = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_BUSINESS_DAY_CLOSED = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RECONCILIATION_ALREADY_PERFORMED = 19,
    }
}
